language: php
php:
  - 5.4
  - 5.5
  - 5.6

matrix:
    allow_failures:
        - php: 5.4

before_install:
    - if [ $TRAVIS_PHP_VERSION = '5.6' ]; then COVERAGE="-c `php -i | grep 'xdebug.ini'` --coverage coverage.xml --coverage-src src/"; else COVERAGE="" && if [ $TRAVIS_PHP_VERSION = '5.6' ]; then phpenv config-rm xdebug.ini; fi; fi

install:
  - composer install --no-interaction --prefer-source

script:
    - vendor/bin/phpcs --standard=standards.xml --extensions=php --encoding=utf-8 -sp src/
    - vendor/bin/tester -p php $COVERAGE tests/